version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Release
- Debug

init:
- ps: $env:APPVEYOR_CACHE_SKIP_SAVE = "true"

before_build:
- cmd: >-

    git submodule update --init --recursive
    
    if exist build\ rd /s /q build
    
    if not exist build\ mkdir build

    cd build
    
    cmake -G "Visual Studio 15 2017 Win64" ../
    
build:
  project: C:\projects\spacerocks\build\PACKAGE.vcxproj
  parallel: true
  verbosity: minimal
  
after_build:
- cmd: >-

    7z a SpaceRocks%CONFIGURATION%_win64.zip %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/SpaceRocks.exe %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/*.dll  %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/**/*
    
    cd C:/projects/spacerocks/build/
    
    if not exist installer/ mkdir installer
    
    cd C:/projects/spacerocks/build/installer/
    
    dir
    
    for %%a in (*.exe) do ren "%%~a" "%%~na_%CONFIGURATION%_win64%%~xa"
    
    dir
    
artifacts:
  - path: build/*.zip
    name: SpaceRocks_zip
  - path: build/installer/*.exe
    name: SpaceRocks_installer
    
deploy:
- provider: GitHub
  on:
    appveyor_repo_tag: true
    CONFIGURATION: Release
  auth_token:
    secure: ECVq3ge/gI4xSJEeoXNUiE3fq0samUls/hSKmaGeJmk3CAxEqr02LX2tcVenpINm
  artifact: SpaceRocks_installer, SpaceRocks_zip
  prerelease: true
